plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.147'
    id "me.modmuss50.mod-publish-plugin" version "2.0.0"
}

version = "${project.mod_version}"
group = project.maven_group

base {
    archivesName = 'grabvillager-neoforge'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

sourceSets {
    main {
        java {
            srcDir 'src/client/java'
        }
        resources {
            srcDir 'src/client/resources'
        }
    }
}

processResources {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            neoforge_version       : neoforge_version,
            version                : mod_version
    ]
    inputs.properties replaceProperties

    filesMatching('META-INF/neoforge.mods.toml') {
        expand replaceProperties
    }
}

neoForge {
    version = project.neoforge_version

    runs {
        client {
            client()
        }
        server {
            server()
        }
    }

    mods {
        grabvillager {
            sourceSet sourceSets.main
        }
    }
}

publishMods {
    file = jar.archiveFile
    changelog = providers.fileContents(layout.projectDirectory.file("CHANGELOG.md")).asText.get()
    type = STABLE
    version = "${project.mod_version}-neoforge"
    modLoaders.add("neoforge")

    curseforge {
        displayName = file.map { it.asFile.name }
        projectId = project.curseforge_id
        accessToken = providers.environmentVariable("CURSEFORGE_TOKEN")
        changelogType = "markdown"

        minecraftVersionRange {
            start = "26.2"
            end = "26.2"
        }

        client = true
        server = true
    }

    modrinth {
        displayName = "Grab Villager NeoForge ${project.mod_version}"
        projectId = project.modrinth_id
        accessToken = providers.environmentVariable("MODRINTH_TOKEN")

        minecraftVersionRange {
            start = "26.2"
            end = "26.2"
        }
    }
}