# Project
version=1.0.0
group=com.atom.grabvillager
java_version=21

# Common
minecraft_version=1.21.4
mod_name=Grab Villager
mod_author=atom
mod_id=grabvillager
license=CC0-1.0
credits=
description=The description of your mod.
# On restreint la compatibilité pour qu'elle commence à la 1.21.4
minecraft_version_range=[1.21.4, 1.22)

# Mappings (Adaptés avec la date de sortie officielle de la 1.21.4)
neo_form_version=1.21.4-20241203.161809
parchment_minecraft=1.21.4
parchment_version=2025.03.23

# Fabric
fabric_version=0.114.0+1.21.4
fabric_loader_version=0.18.2

# Forge (La branche 1.21.4 de Forge correspond à la version 54)
forge_version=54.0.0
forge_loader_version_range=[54,)

# NeoForge (La branche 1.21.4 de NeoForge correspond à la version 21.4.x)
neoforge_version=21.4.157
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false