modLoader="javafml"
loaderVersion="[2.1,)"
license="MIT"
issueTrackerURL="https://github.com/TonNom/Grab_Villager/issues"
displayURL="https://modrinth.com/mod/ton-mod"

[[mods]]
modId="grab_villager"
version="${version}"
displayName="Grab Villager"
description="Un mod pour porter les villageois !"
authors="Toi"

# Dépendance à NeoForge
[[dependencies.grab_villager]]
modId="neoforge"
type="required"
versionRange="[21.0,)"
ordering="NONE"
side="BOTH"

# Dépendance à MINECRAFT (Plages 1.21.x ET 26.x)
[[dependencies.grab_villager]]
modId="minecraft"
type="required"
versionRange="[1.21,1.22),[26,27)"
ordering="NONE"
side="BOTH"