modLoader="javafml"
loaderVersion="[21,)"
license="MIT"
issueTrackerURL=""

[[mixins]]
config="grabvillager.mixins.json"

[[mods]]
modId="grabvillager"
version="1.0.0"
displayName="Grab Villager"
authors="Atom"
description="Attrape et lance des villageois librement !"

[[dependencies.grabvillager]]
modId="neoforge"
type="required"
versionRange="[21,)"
ordering="NONE"
side="BOTH"

[[dependencies.grabvillager]]
modId="minecraft"
type="required"
versionRange="[1.21,1.22)"
ordering="NONE"
side="BOTH"